name: Build kernel (Run workflow on build-kernel branch)
on:
  workflow_dispatch:
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: |
           echo -e "\e[31mThis is Red Text\e[0m"
           echo -e "\e[32mThis is Green Text\e[0m"
           echo -e "\e[34mThis is Blue Text\e[0m"
           echo -e "\e[33mThis is Yellow Text\e[0m"
