name: Build kernel (Run workflow on build-kernel branch)
on:
  workflow_dispatch:
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        shell: bash
        run: |
          echo "RED=\033[0;31m" >> $GITHUB_ENV
          echo "GREEN=\033[0;32m" >> $GITHUB_ENV
          echo "NORMAL=\033[0m" >> $GITHUB_ENV
          echo -e "${{ env.GREEN }}Hello${{ env.NORMAL }}"
